<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Vehistra.Reporting</RootNamespace>
    <AssemblyName>Vehistra.Reporting</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vehistra.Application\Vehistra.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" />
  </ItemGroup>

</Project>
